WebHook:
  RSAToken: ""


server:
  port: 8081

spring:
  application:
    name: GP
  data:
    mongodb:
      host: 192.168.0.103
      username: mongoadmin
      password: mongoadmin

BotAddress: "http:"

#线程池
corePoolSize: 5
maxPoolSize: 30
keepAliveTime: 30
queueCapacity: 100
threadName: "Plugin:"
logging:
  level:
    root: info
    com.ecturing.Gp: info

