WebHook:
  RSAToken: ""


server:
  port: 8080

spring:
  application:
    name: GP


#线程池
corePoolSize: 5
maxPoolSize: 30
keepAliveTime: 30
queueCapacity: 100
threadName: "Plugin:"

#log级别
logging:
  level:
    root: info
    com.ecturing.gp: info

